---
- hosts: all

  vars_files: 
    - vars/wordpress.yml
    - vars/vault.yml
  roles:
    - { role: geerlingguy.nginx, tags: [nginx]}
    - { role: geerlingguy.php, tags: [php]}
    - { role: geerlingguy.mysql, tags: [mysql]}
    - { role: wordpress, tags: [wordpress, app]}