telegram_token: 1818195686:AAFA8p_q62f7Iy5hZsFFTiiaIyQocIRPURM
 # ONLY IF YOU USING TEMPLATE required for test

template_path: "template.tmpl" 
time_zone: "Europe/Moscow"
split_token: "|"    

# ONLY IF YOU USING DATA FORMATTING FUNCTION, NOTE for developer: important or test fail
time_outdata: "02/01/2006 15:04:05" 
split_msg_byte: 4000