version: "3.7"

volumes:
  elasticsearch_volume:

services:
  fluentd:    
    build: 
      context: ./configs/fluentd
    container_name: fluentd      
    volumes:
      - ./configs/fluentd/plugins:/fluentd/plugins:rw
      - ./configs/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G               

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.9.2
    container_name: apm-server
    volumes:
      - ./configs/apm_elastic/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro    
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - "8200:8200"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G   

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G               

  kibana:
    image: kibana:7.13.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G               
  
  pyapp:
    build:
      context: ./app/pyapp
    ports:
      - 808:8080
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G

  goapp:
    build:
      context: ./app/goapp
    environment:
      ELASTIC_APM_SERVICE_NAME: GoApp
      ELASTIC_APM_SERVER_URL: http://apm-server:8200 
    ports:
      - 801:8080
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G

  jsapp:
    build:
      context: ./app/jsapp
    ports:
      - 803:3000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G