services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./conf.d/:/etc/nginx/conf.d/
      - ./www/:/var/www/
      - ./other/:/etc/nginx/other/
    # command:
    #   - '--with-http_stub_status_module'
    restart: unless-stopped
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G         