# Format version 2.1 was introduced with Docker Compose v1.9
# We need Docker Compose v1.9+ for unset variable interpolation
version: "2.1"

# BRAVE_EXAMPLE choices are listed here https://github.com/openzipkin/brave-example#example-projects

services:
  # Generate traffic by hitting http://localhost:8081
  frontend:
    container_name: frontend
    image: ghcr.io/openzipkin/brave-example:${BRAVE_EXAMPLE:-armeria}
    entrypoint: start-frontend
    ports:
      - 8881:8081
    depends_on:
      backend:
        condition: service_healthy
      zipkin:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G  
  # Serves the /api endpoint the frontend uses
  backend:
    container_name: backend
    image: ghcr.io/openzipkin/brave-example:${BRAVE_EXAMPLE:-armeria}
    entrypoint: start-backend
    depends_on:
      zipkin:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G          
  # View traces at http://127.0.0.1:19411/zipkin
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - 19411:9411
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G        
